language: python

python:
  - "3.7"
  
install:
  - pip install -r requirements.txt
  - pip install --user numpy scipy matplotlib ipython jupyter pandas sympy nose
  
script:
  - make test

branches:
  only:
    - master
