language: python

python:
  - "3.7"
  
install:
  - pip install ".[test]" . # install package + test dependencies
  
script:
  - pytest

branches:
  only:
    - master
after_success:
  - codecov # submit coverage
